catalog: lake_commerce
schema: catalogo
name: produto_fornecedor
description: "Tabela que relaciona produtos e fornecedores."
tags:
  update_method: batch
columns:
  - name: pk_produto_fornecedor
    type: STRING
    description: "Identificador único da relação entre produto e fornecedor."
    tags:
      pii: false
  - name: fk_produto
    type: STRING
    description: "Chave estrangeira que referencia o produto."
    foreign_key:
      catalog: lake_commerce
      schema: catalogo
      table: produto
      column: pk_produto
    tags:
      pii: false
  - name: fk_fornecedor
    type: STRING
    description: "Chave estrangeira que referencia o fornecedor."
    foreign_key:
      catalog: lake_commerce
      schema: catalogo
      table: fornecedor
      column: pk_fornecedor
    tags:
      pii: false
  - name: preco_compra
    type: DECIMAL(10,2)
    description: "Preço de compra do produto."
    tags:
      pii: false