catalog: lake_commerce
schema: catalogo
name: produto
description: "Tabela que armazena os produtos disponíveis no e-commerce."
tags:
  update_method: batch
columns:
  - name: pk_produto
    type: STRING
    description: "Identificador único do produto."
    tags:
      pii: false
  - name: nome
    type: STRING
    description: "Nome do produto."
    tags:
      pii: false
  - name: descricao
    type: TEXT
    description: "Descrição detalhada do produto."
    tags:
      pii: false
  - name: preco
    type: DECIMAL(10,2)
    description: "Preço do produto."
    tags:
      pii: false
  - name: estoque
    type: INT
    description: "Quantidade em estoque."
    tags:
      pii: false
  - name: fk_categoria
    type: STRING
    description: "Chave estrangeira que referencia a categoria do produto."
    foreign_key:
      catalog: lake_commerce
      schema: catalogo
      table: categoria
      column: pk_categoria
    tags:
      pii: false